# Generated by Django 4.0.2 on 2022-03-17 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тип ткани')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('photo', models.ImageField(null=True, upload_to='img/', verbose_name='Изображение')),
                ('color', models.CharField(max_length=40, verbose_name='Цвет ткани')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('on_view_price', models.BooleanField(default=True, verbose_name='Отобразить цену')),
                ('type_cl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.types')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежды',
            },
        ),
    ]
