# Generated by Django 4.0.2 on 2022-03-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothing',
            options={'ordering': ('-id',), 'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежды'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'ordering': ('-id',), 'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='on_view_price',
        ),
        migrations.AddField(
            model_name='clothing',
            name='on_view_post',
            field=models.BooleanField(default=True, verbose_name='Отобразить публикацию'),
        ),
    ]
